core/src/batch/emit.rs
core/src/batch/mod.rs
core/src/batch/rxtx.rs
core/src/batch/send.rs

* changed emit to transmit the packet to a different q right away.
* also changed the tests to use a mpsc instead of plain vec for rx and tx. vec is not flexible enough for assertions because it can only be owned by the pipeline.

emit to specific outbound q

---

core/src/batch/filter.rs
core/src/batch/filter_map.rs
core/src/batch/for_each.rs
core/src/batch/map.rs
core/src/batch/mod.rs
core/src/batch/send.rs

We are cloning the mbufs before transferring the ownership of the packet to `map` or `filter_map` function. So if the function throws an error, we will queue the clone up for a bulk drop later. This approach is actually problematic. Without reference counting the clones, the first copy that goes out of scope will cause the mbuf to be returned to the mempool. The additional clone could erroneously free something it in fact no longer owns. To avoid this problem, we will not clone mbufs anymore inside the combinators. The downside is, on errors, mbufs will not be bulk freed.

avoid cloning packets in batch combinators

---

core/src/batch/group_by.rs
core/src/batch/mod.rs
examples/pktdump/main.rs

small refactoring to make `compose!` loosely mimics the match expression.

refactor compose! to mimic match

---

core/src/dpdk/kni.rs
core/src/dpdk/mempool.rs
core/src/dpdk/port.rs
core/src/dpdk/stats.rs
core/src/metrics.rs
core/src/runtime/mempool_map.rs
core/src/runtime/mod.rs
examples/kni/Cargo.toml
examples/kni/main.rs

sample output of KNI stats
```
---
nb2:
kni:
"dropped{kni=\"kni0\",dir=\"tx\"}": 0
"octets{kni=\"kni0\",dir=\"rx\"}": 6460
"octets{kni=\"kni0\",dir=\"tx\"}": 0
"packets{kni=\"kni0\",dir=\"rx\"}": 64
"packets{kni=\"kni0\",dir=\"tx\"}": 0
port:
"dropped{port=\"kni0\",dir=\"rx\"}": 0
"dropped{port=\"kni0\",dir=\"tx\"}": 0
"errors{port=\"kni0\",dir=\"rx\"}": 0
"errors{port=\"kni0\",dir=\"tx\"}": 0
"no_mbuf{port=\"kni0\",dir=\"rx\"}": 0
"octets{port=\"kni0\",dir=\"rx\",core=\"1\"}": 0
"octets{port=\"kni0\",dir=\"tx\",core=\"1\"}": 6460
"packets{port=\"kni0\",dir=\"rx\",core=\"1\"}": 0
"packets{port=\"kni0\",dir=\"tx\",core=\"1\"}": 64
```
sample output of mempool stats
```
---
nb2:
mempool:
"free{pool=\"mempool0\"}": 65151
"used{pool=\"mempool0\"}": 384
```

kni and mempool stats

---

core/src/dpdk/port.rs

Stats mapping breaks virtual dev drivers like net_ring and net_pcap. Turns out the documentation didn't make this very clear. You only need to call these 2 functions to remap the queue to stats mapping. Did some spot checking, and seems like all drivers are keeping per queue stats without needing to call these functions. The queue index maps to stats index, exactly what we need anyway. We can delete these calls.

fix: stats mapping breaks net_ring and net_pcap

---

core/Cargo.toml

turns out we do need to repeat criterion in dev deps too. otherwise if you try to run `cargo test` from the core subdir, you get this nice compilation message.
```
root@ubuntu-bionic:/opt/shitbricks/core# cargo test
Compiling nb2 v0.1.0 (/opt/shitbricks/core)
error[E0432]: unresolved import `criterion`
--> core/src/testils/criterion.rs:2:5
|
2 | use criterion::{black_box, Bencher};
|     ^^^^^^^^^ help: a similar path exists: `super::criterion`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
error: could not compile `nb2`.
```
not exactly sure why, but too lazy to find out. so we will add it back in both places. reason it's nice to run tests from the subdir is if I'm making breaking changes. would be nice to make sure core compiles …

fix cargo test from a subdir

---

core/src/dpdk/mbuf.rs
core/src/packets/ethernet.rs

Add support for VLAN ethernet frame parsing. It only identifies the two types of VLAN frames and make sure that the payload is parsed correctly accounting for the change in offset. This does not handle writing to a VLAN frame, or pushing a new VLAN frame.

parse ethernet vlan packets

---

ffi/Cargo.toml

For some reason we must pin `bindgen` to the exact revision here. If we don't somehow it could end up generating bad bindings that fails to compile. not sure what causes the resolution to behave differently, but pinning it to the exact revision seems to fix the issue.
```
Compiling config v0.9.3
error[E0204]: the trait `Copy` may not be implemented for this type
--> /opt/semantics/target/debug/build/nb2-ffi-3c915c134b754cad/out/bindings.rs:18511:26
|
18511 | #[derive(Debug, Default, Copy, Clone, PartialEq)]
|                          ^^^^
...
18519 |     pub pkts: __IncompleteArrayField<*mut rte_mbuf>,
|     ----------------------------------------------- this field does not implement `Copy`
error[E0204]: the trait `Copy` may not be implemented for this type
--> …
```

pin bindgen to revision 0.51.1

---

core/src/batch/group_by.rs
core/src/net/mod.rs
core/src/settings.rs
core/src/testils/proptest/strategy.rs

a collection of small fixes
* the `GroupByBatchBuilder` is only called once, hence it should be `FnOnce`.
* the `Cidr` trait is re-exported at testils top level like other types.
* make config setting structs clonable.
* randomly generated `segments_left` by proptest should be `u8`.

miscellaneous fixes

---

core/src/testils/proptest/strategy.rs
core/src/testils/rvg.rs

small fix. the rvg api is not consistent between `generate` and `generate_vec`, now they both accept the strategy by ref.

generate takes strategy by ref

---

core/src/dpdk/port.rs
core/src/runtime/mod.rs
core/src/settings.rs

makes the promiscuous mode configurable. the default is `false`.

make port promiscuous mode configurable

---

core/src/packets/checksum.rs
core/src/packets/icmp/v6/mod.rs
core/src/packets/icmp/v6/time_exceeded.rs
core/src/packets/icmp/v6/too_big.rs
core/src/packets/ip/mod.rs
core/src/packets/ip/v4.rs
core/src/packets/ip/v6/fragment.rs
core/src/packets/ip/v6/mod.rs
core/src/packets/ip/v6/srh.rs

adds support for ICMPv6 Time Exceeded message. also fixing how truncate was implemented to account for dynamically sized ethernet frames. the old implementation doesn't work if there are vlan tags on the ethernet frames.

icmpv6 time exceeded

---

core/src/batch/group_by.rs
core/src/batch/mod.rs

- reasoning: `|` is not allowed in macro_rules, but the comma still makes
sense

group-by with or (via `,`, like in erlang)

---

core/src/batch/group_by.rs
core/src/dpdk/kni.rs
core/src/dpdk/mbuf.rs
core/src/dpdk/mod.rs
core/src/dpdk/port.rs
core/src/packets/ethernet.rs
core/src/packets/icmp/v4/mod.rs
core/src/packets/icmp/v6/mod.rs
core/src/packets/ip/v4.rs
core/src/packets/ip/v6/fragment.rs
core/src/packets/ip/v6/mod.rs
core/src/packets/ip/v6/srh.rs
core/src/packets/mbuf.rs
core/src/packets/mod.rs
core/src/packets/tcp.rs
core/src/packets/udp.rs
core/src/pcap.rs
macros/src/derive_packet.rs

fixes #76. `Mbuf` is freed only once and packets are no longer publicly clonable.

fix prematurely freeing the message buffer

---

examples/nat64/README.md
examples/nat64/main.rs

two pipelines for eth1 -> eth2 and eth2 -> eth1

6 to 4 & 4 to 6 installs

---

.github/workflows/main.yml
ffi/build.rs

Related to change in https://github.com/capsule-rs/sandbox/pull/14 as we move away from native arch instructions. Will need that new container for CI to pass.

use transportable -m arch

---

.github/workflows/main.yml

@drunkirishcoder tarpaulin hits an error when running it within core. So, let's use nightly (like we do for sanitize) and get the right feature. I think that's ok for coverage (since we test stable separately).

oh tarpaulin

---

core/src/packets/ethernet.rs

`EthernetHeader` is defined as a union. The size of the union is 22 bytes even though a tagless header only needs 14 bytes. On push the buffer is extended by 14 bytes, so the 8-byte overflow will corrupt the data following the extended segment. This fixes the bug by only writing 14 bytes.

fix push ethernet corrupts data

---

core/src/batch/group_by.rs
core/src/batch/mod.rs

Add support for using fanout combinators in a `group_by` sub-batch. `group_by` no longer assumes that the sub-batch will return a single packet for every input packet. This fixes #25.

support fanout combinators in group by

---

core/src/dpdk/kni.rs
core/src/dpdk/mbuf.rs
core/src/dpdk/mempool.rs
core/src/dpdk/mod.rs
core/src/dpdk/port.rs
core/src/dpdk/stats.rs
core/src/ffi.rs
core/src/lib.rs
core/src/pcap.rs

- minimizes feature-flag configuration attributes for pcap-dump
- adds new AsStr/ToResult impls for ffi/lib conversions
- cleans up function call usage and consistent formatting
- leverages callback user_param to pass port name for pcap create/append

Make pcap-dump feature use dpdk rx/tx callback

---

.github/workflows/main.yml

- remove need for codecov token in codecov action
* action doesn't need it in public repos and will cause issues w/ forks where secrets don't persist
- comment out coverage job until https://github.com/xd009642/tarpaulin/issues/461 is solved.
- comment out `critcmp` comparison on bench-pr due to issue ~ https://github.com/BurntSushi/critcmp/issues/5.

minor ci update around coverage/bench compare (we've seen issues in prs)

---

core/src/packets/icmp/v4/mod.rs
core/src/packets/icmp/v4/redirect.rs

Adds support for ICMPv4 Redirect Message defined in IETF RFC 792

Add icmpv4 redirect message

---

.github/workflows/main.yml

due to https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets & https://github.community/t/make-secrets-available-to-builds-of-forks/16166

continue on error for notifiers b/c fork pr issue with secrets

---

Makefile
core/src/dpdk/mempool.rs
core/src/net/cidr/mod.rs
core/src/net/cidr/v4.rs
core/src/net/cidr/v6.rs
core/src/net/mod.rs

Enhance our CIDR trait and increase testing coverage on the mod. Obviously, always down for further cleanup and better comments.

update cidr methods

---

.github/workflows/main.yml

per https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

update main.yml for manually dispatch

---

core/Cargo.toml
examples/kni/Cargo.toml
examples/kni/main.rs
examples/syn-flood/Cargo.toml
examples/syn-flood/main.rs

~Fixes the security advisory failure on [sized-chunks](https://rustsec.org/advisories/RUSTSEC-2020-0041.html).~

bump metrics lib to 0.13

---

.github/workflows/main.yml
README.md
core/src/lib.rs
core/src/pcap.rs
core/src/runtime/mod.rs
ffi/build.rs

- Fixes #119 with changes to meson/clang
- Move to Rust 1.49
* assoc clippy changes
- Test/move to Dpdk 19.11.6
* updated pcap open_dump doesn't err on empty file, so check for first
- Associated PR on sandbox: https://github.com/capsule-rs/sandbox/pull/21

Fix for ffi #119 and move to rust 1.49

---

.github/workflows/main.yml

Fixes the broken `bench` job. The location of the Criterion report seems to have changed from `./bench/target/criterion` to `./target/criterion`.

change criterion report location

---

bench/packets.rs
core/src/packets/ip/v6/srh.rs
core/src/packets/mod.rs
core/src/packets/tcp.rs
core/src/packets/udp.rs
core/src/testils/packet.rs
core/src/testils/proptest/strategy.rs
examples/nat64/main.rs
examples/pktdump/main.rs
examples/syn-flood/main.rs

A small quality of life improvement by introducing a couple `Tcp` and `Udp` aliases. Instead of writing
```
let udp = packet.parse::<Tcp<Ipv4>>()?;
```
you can now write
```
let udp = packet.parse::<Tcp4>()?;
```

introduce tcp and udp aliases

---

examples/syn-flood/README.md
examples/syn-flood/main.rs

Send the `SYN` packets to `eth3` so they can be observed with `tcpdump` for example.

send syn flood to eth3
